"""Initial migration with all models

Revision ID: 0adbb0da966d
Revises: 
Create Date: 2026-04-30 11:05:56.562159
"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '0adbb0da966d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('api_key', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_users_api_key'), 'users', ['api_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_api_key'), table_name='users')
    op.drop_column('users', 'api_key')
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
