"""initial_migration

Revision ID: daffcdf14a7a
Revises: 
Create Date: 2026-04-30 09:38:41.195446
"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'daffcdf14a7a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
